version: '3'

volumes:
  db_data:

services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

  # mongodb:
  # image: mongo:latest

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
